# Generated by Django 4.1.1 on 2022-10-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='src',
            field=models.CharField(max_length=300),
        ),
    ]
